server:
  port: 8080
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods: '*'
            allowCredentials: true
logging:
  config: classpath:logback-spring.xml
