server:
  port: 8080
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
spring:
  application:
    name: provider-boot-mall
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/WEB-INF/static/
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
    deserialization:
      fail_on_unknown_properties: false
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    parser:
      allow_single_quotes: true
      allow_unquoted_control_chars: true
  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:/WEB-INF/templates/
    mode: HTML5
    suffix: .html
logging:
  config: classpath:logback-spring.xml
